#
# dotphiles : https://github.com/dotphiles/dotphiles
#
# Sets dotzsh options.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#   Ben O'Hara <bohara@gmail.com>
#

# Set the key mapping style to 'emacs' or 'vi'.
zstyle ':dotzsh:module:editor' keymap 'vi'
zstyle ':dotzsh:module:editor' editor 'vi'

# Auto convert .... to ../..
zstyle ':dotzsh:module:editor' dot-expansion 'yes'

# Set case-sensitivity for completion, history lookup, etc.
zstyle ':dotzsh:module:*' case-sensitive 'no'

# Color output (auto set to 'no' on dumb terminals).
zstyle ':dotzsh:module:*' color 'yes'

# Setup aliases for modules (disable per module below).
zstyle ':dotzsh:module:*' aliases 'yes'

# Auto set the tab and window titles.
zstyle ':dotzsh:module:terminal' auto-title 'yes'

zstyle ':dotzsh:module:ssh:agent' forwarding 'yes'
zstyle ':dotzsh:module:ssh:aliases' hosts 'yes'

zstyle ':dotzsh:module:syntax-highlighting' highlighters 'main' 'brackets' 'pattern' \
  'cursor' 'root' \

# Set the Zsh modules to load (man zshmodules).
zstyle ':dotzsh:load' zmodule 'stat'

# Set the Zsh functions to load (man zshcontrib).
zstyle ':dotzsh:load' zfunction 'zargs' 'zmv'

# Set the dotzsh modules to load (browse modules).
# The order matters.
zstyle ':dotzsh:load' dzmodule \
  'environment' \
  'terminal' \
  'editor' \
  'history' \
  'utility' \
  'completion' \
  'theme' \
  'syntax-highlighting' \
  'history-substring-search' \
  'git' \
  'z'

# Set the theme to load.
# Setting it to 'random' loads a random theme.
# Auto set to 'off' on dumb terminals.
zstyle ':dotzsh:module:theme' theme 'dotphiles'
# Set custom scheme based on hostname or domain
#zstyle ':dotzsh:module:theme:host:hostname' theme 'dotphiles' 'soldark' 'yellow'
#zstyle ':dotzsh:module:theme:host:hostname2.example2.com' theme 'dotphiles' 'soldark' 'violet'
#zstyle ':dotzsh:module:theme:domain:example.net' theme 'dotphiles' 'soldark' 'red'

# Load dotzsh
source "$DOTZSH/init.zsh"

# Customize to your needs...

## Directory Helpers ##########
function stash {
  rm ~/.snatch-files/* -rf
  cp $@ ~/.snatch-files/. -rf
}
function unstash {
  cp ~/.snatch-files/* . -rf
}
function snip {
  head -n$2 $3 | tail -n$(expr $2 - $1)
}
function sd {
  echo $PWD > ~/.stored-directory
  echo Stored $PWD
}
function rd {
  local dir=`cat ~/.stored-directory`
  echo Resumed $dir
  cd $dir
}

## Uncategorized Aliases ##########
alias vi="vim -p"

## TMUX ##########
alias tmux='/home/wesalvaro/third_party/tmux/tmux-1.6/tmux'
alias xa='tmux at -t'
alias xd='tmux at -d -t'
alias xs='tmux new -s'
alias xls='tmux ls'
alias xl='tmux at'

## Git ##########
export GIT_CEILING_DIRECTORIES=/home/wesalvaro/src
alias lsb='git branch'
alias mvb='git branch -m'
alias rmb='git branch -D'
alias rollback='git reset --hard HEAD~1'
alias unci='git reset --soft HEAD~1'
alias a='git camend'
alias aa='git camend -a'
alias amend='git camend -a'
alias b='git checkout -b'
alias cancel='git reset --hard HEAD'
alias co='git checkout'
alias g=git
function ca {
  local f="/home/wesalvaro/commits"
  if git commit -a -m "$1" >> $f; then
    echo "$(date) [$PWD]" >> $f
    echo >> $f
    tail -n5 $f
  fi;
}
function ci {
  local f="/home/wesalvaro/commits"
  if git commit -m "$1" >> $f; then
    echo $(date) [$PWD] >> $f
    echo >> $f
    tail -n5 $f
  fi;
}
alias tag='git tag -f'
alias huh='git show-branch'
function killp {
  ps ua | grep -i "port=$1" | awk '{ print $2 }' | xargs kill
}
alias geeknote='python /home/wesalvaro/third_party/geeknote/geeknote.py'
function snip {
  geeknote create --title "$*" -c "$PWD\n`git show-branch`" --tags "snippet" --notebook "Work"
}
alias snips='geeknote find'

## Random Scripts ##########
alias db='/home/wesalvaro/public/db'

## Some ls aliases ##########
alias ls='ls -la --color'
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

## Google Proprietary ##########
if test -f /home/wesalvaro/.zsh-goog; then
  source /home/wesalvaro/.zsh-goog
fi;

