#
# dotphiles : https://github.com/dotphiles/dotphiles
#
# Sets dotzsh options.
#
# Authors:
#   Ben O'Hara <bohara@gmail.com>
#

# debug: see with `dzinfo`
##zstyle ':dotzsh:load' timing 'yes'
##zstyle ':dotzsh:module:*' timing 'yes'

# Set the key mapping style to 'emacs' or 'vi'.
zstyle ':dotzsh:module:editor' keymap 'vi'
zstyle ':dotzsh:module:editor' editor 'vi'

# Auto convert .... to ../..
zstyle ':dotzsh:module:editor' dot-expansion 'yes'

# Set case-sensitivity for completion, history lookup, etc.
zstyle ':dotzsh:module:*' case-sensitive 'no'

# Color output (auto set to 'no' on dumb terminals).
zstyle ':dotzsh:module:*' color 'yes'

# Setup aliases for modules (disable per module below).
zstyle ':dotzsh:module:*' aliases 'yes'

# Auto set the tab and window titles.
zstyle ':dotzsh:module:terminal' auto-title 'yes'

zstyle ':dotzsh:module:ssh:agent' forwarding 'yes'
zstyle ':dotzsh:module:ssh:aliases' hosts 'yes'

zstyle ':dotzsh:module:syntax-highlighting' highlighters 'main' 'brackets' 'pattern' 'cursor' 'root'

# Set the Zsh modules to load (man zshmodules).
zstyle ':dotzsh:load' zmodule 'stat'

# Set the Zsh functions to load (man zshcontrib).
zstyle ':dotzsh:load' zfunction 'zargs' 'zmv'

# Set the dotzsh modules to load (browse modules).
# The order matters.
zstyle ':dotzsh:load' dzmodule \
  'aliaster' \
  'gnu-utility' \
  'environment' \
  'terminal' \
  'editor' \
  'history' \
  'utility' \
  'completion' \
  'theme' \
  'history-substring-search' \
  'z'
  #'syntax-highlighting' \
  #'git' \

### Global settings
# Color output (auto set to 'no' on dumb terminals).
zstyle ':dotzsh:module:*' color 'yes'
# Setup aliases for modules (disable per module below).
zstyle ':dotzsh:module:*' aliases 'yes'
# Set case-sensitivity for completion, history lookup, etc.
zstyle ':dotzsh:module:*' case-sensitive 'no'

### Environment module
# Set which PAGER to use less or more
##zstyle ':dotzsh:module:environment' pager 'less'
# Enable mouse scrolling in less, add the following to *zshrc*
##zstyle ':dotzsh:module:environment:pager:less' mousescroll 'false'

### Terminal Module
# Auto set the tab and window titles.
zstyle ':dotzsh:module:terminal' auto-title 'yes'

### Editor module
# Set the key mapping style to 'emacs' or 'vi'.
zstyle ':dotzsh:module:editor' keymap 'emacs'
# Set EDITOR to 'emacs' or 'vi'.
zstyle ':dotzsh:module:editor' editor 'vi'
# Auto convert .... to ../..
#zstyle ':dotzsh:module:editor' dot-expansion 'yes'

### Global settings
# Color output (auto set to 'no' on dumb terminals).
zstyle ':dotzsh:module:*' color 'yes'
# Setup aliases for modules (disable per module below).
zstyle ':dotzsh:module:*' aliases 'yes'
# Set case-sensitivity for completion, history lookup, etc.
zstyle ':dotzsh:module:*' case-sensitive 'no'

### Environment module
# Set which PAGER to use less or more
##zstyle ':dotzsh:module:environment' pager 'less'
# Enable mouse scrolling in less, add the following to *zshrc*
##zstyle ':dotzsh:module:environment:pager:less' mousescroll 'false'

### Terminal Module
# Auto set the tab and window titles.
zstyle ':dotzsh:module:terminal' auto-title 'yes'

### Editor module
# Set the key mapping style to 'emacs' or 'vi'.
zstyle ':dotzsh:module:editor' keymap 'emacs'
# Set EDITOR to 'emacs' or 'vi'.
zstyle ':dotzsh:module:editor' editor 'vi'
# Auto convert .... to ../..
#zstyle ':dotzsh:module:editor' dot-expansion 'yes'

### Utility Module
# Disable `diff` highlighting
##zstyle ':dotzsh:module:utility:diff' color 'no'
# Disable `wdiff` highlighting
##zstyle ':dotzsh:module:utility:wdiff' color 'no'
# Disable `make` highlighting
##zstyle ':dotzsh:module:utility:make' color 'no'

### Completion module
# Expand global aliases automatically
#zstyle ':dotzsh:module:completion' expand-global-aliases 'yes'

### SSH module
zstyle ':dotzsh:module:ssh:agent' forwarding 'yes'
#zstyle ':dotzsh:module:ssh:aliases' hosts 'yes'
##zstyle ':dotzsh:module:ssh:agent' identities 'id_rsa' 'id_rsa2' 'id_github'

### GNUPG module
# Enable ssh-agent protocol emulation for gpg-agent
##zstyle ':dotzsh:module:gnupg' agent-ssh-support 'yes'

### OSX module
# Add aliases for Applications
##zstyle ':dotzsh:module:osx' launcher 'yes'
# Open/Resume temrinal in correct dir
##zstyle ':dotzsh:module:osx' terminal-resume 'yes'

### Git module
# Disable all git aliases
##zstyle ':dotzsh:module:git' aliases 'no'

### TMUX module
# Auto start a session when Zsh is launched.
# Setting it to 'local' only starts a session for local terminals.
# Setting it to 'remote' only starts a session for SSH connections.
##zstyle ':dotzsh:module:tmux' auto-start 'no'
#zstyle ':dotzsh:module:tmux:aliases' tmuxinator 'yes'

### Syntax Highlighting module
#zstyle ':dotzsh:module:syntax-highlighting' highlighters 'main' 'brackets' 'pattern' \
#  'cursor' 'root' \

### Theme module
# Set default theme to load.
# Setting it to 'random' loads a random theme.
# Auto set to 'off' on dumb terminals.
zstyle ':dotzsh:module:theme' theme 'sorin'
### Set custom theme based on hostname or domain
# zstyle ':dotzsh:module:theme:hostname:your-host-here' theme 'dotphiles' 'soldark' 'magenta'
# zstyle ':dotzsh:module:theme:hostname:your-other-host-here' theme 'dotphiles' 'soldark' 'violet'
# zstyle ':dotzsh:module:theme:domain:your-domain-here' theme 'dotphiles' 'soldark' 'orange'

### Load dotzsh
source "$DOTZSH/init.zsh"

### Customize to your needs...

## Directory Helpers ##########
function stash {
  rm -rf ~/.snatch-files/*
  cp -rf $@ ~/.snatch-files/.
}
function unstash {
  cp -rf ~/.snatch-files/* .
}
function snip {
  head -n$2 $3 | tail -n$(expr $2 - $1)
}
function sd {
  echo $PWD > ~/.stored-directory
  echo Stored $PWD
}
function rd {
  local dir=`cat ~/.stored-directory`
  echo Resumed $dir
  cd $dir
}
function kgrep {
  pgrep -f $@ | xargs kill
}

## Uncategorized Aliases ##########
alias vi="vim -p"
alias http="python -m SimpleHTTPServer"
alias ack="ack-grep"
alias py='ipython'
alias db='/home/wesalvaro/public/db'
alias csslint="node ~/.npm/csslint/0.9.10/package/cli.js"
alias geeknote='python /home/wesalvaro/third_party/geeknote/geeknote.py'

## TMUX ##########
alias xa='tmux at -t'
alias xd='tmux at -d -t'
alias xs='tmux new -s'
alias xls='tmux ls'
alias xl='tmux at'

## Git ##########
export GIT_CEILING_DIRECTORIES=/usr/local/google/home/wesalvaro/src
alias lsb='git branch'
alias mvb='git branch -m'
alias rmb='git branch -D'
alias rollback='git reset --hard HEAD~1'
alias unci='git reset --soft HEAD~1'
alias g=git
function ca {
  local f="~/commits"
  if git commit -a -m "$1" >> $f; then
    echo "$(date) [$PWD]" >> $f
    echo >> $f
    tail -n5 $f
  fi;
}
function ci {
  local f="~/commits"
  if git commit -m "$1" >> $f; then
    echo $(date) [$PWD] >> $f
    echo >> $f
    tail -n5 $f
  fi;
}
alias tag='git tag -f'
alias huh='git show-branch'
function killp {
  ps ua | grep -i "port=$1" | awk '{ print $2 }' | xargs kill
}
function snip {
  geeknote create --title "$*" -c "$PWD\n`git show-branch`" --tags "snippet" --notebook "Work"
}
alias snips='geeknote find'

## Random Scripts ##########
export GOPATH=~/gocode

## Some ls aliases ##########
alias ls='ls -la --color'
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

## Google Proprietary ##########
if test -f /usr/local/google/home/wesalvaro/.zshrc.goog; then
  source /usr/local/google/home/wesalvaro/.zshrc.goog
fi;

## PhantomJS ##########
PATH=$PATH:/usr/local/google/home/wesalvaro/third_party/phantomjs-1.8.2-linux-x86_64/bin

## Node ##########
[[ -s /usr/local/google/home/wesalvaro/.nvm/nvm.sh ]] && . /usr/local/google/home/wesalvaro/.nvm/nvm.sh # This loads NVM

PATH=/usr/local/google/home/wesalvaro/.nvm/v0.10.20/bin:/usr/local/google/home/wesalvaro/third_party/phantomjs-1.9.2-linux-x86_64/bin:/usr/local/google/home/wesalvaro/gocode/bin:$PATH
