#
# dotphiles : https://github.com/dotphiles/dotphiles
#
# Sets dotzsh options.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#   Ben O'Hara <bohara@gmail.com>
#

# Set the key mapping style to 'emacs' or 'vi'.
zstyle ':dotzsh:module:editor' keymap 'vi'
zstyle ':dotzsh:module:editor' editor 'vi'

# Auto convert .... to ../..
zstyle ':dotzsh:module:editor' dot-expansion 'yes'

# Set case-sensitivity for completion, history lookup, etc.
zstyle ':dotzsh:module:*' case-sensitive 'no'

# Color output (auto set to 'no' on dumb terminals).
zstyle ':dotzsh:module:*' color 'yes'

# Setup aliases for modules (disable per module below).
zstyle ':dotzsh:module:*' aliases 'yes'

# Auto set the tab and window titles.
zstyle ':dotzsh:module:terminal' auto-title 'yes'

zstyle ':dotzsh:module:ssh:agent' forwarding 'yes'
zstyle ':dotzsh:module:ssh:aliases' hosts 'yes'

zstyle ':dotzsh:module:syntax-highlighting' highlighters 'main' 'brackets' 'pattern' \
  'cursor' 'root' \

# Set the Zsh modules to load (man zshmodules).
zstyle ':dotzsh:load' zmodule 'stat'

# Set the Zsh functions to load (man zshcontrib).
zstyle ':dotzsh:load' zfunction 'zargs' 'zmv'

# Set the dotzsh modules to load (browse modules).
# The order matters.
zstyle ':dotzsh:load' dzmodule \
  'environment' \
  'terminal' \
  'editor' \
  'history' \
  'utility' \
  'completion' \
  'theme'

# Set the theme to load.
# Setting it to 'random' loads a random theme.
# Auto set to 'off' on dumb terminals.
zstyle ':dotzsh:module:theme' theme 'dotphiles'
# Set custom scheme based on hostname or domain
#zstyle ':dotzsh:module:theme:host:hostname' theme 'dotphiles' 'soldark' 'yellow'
#zstyle ':dotzsh:module:theme:host:hostname2.example2.com' theme 'dotphiles' 'soldark' 'violet'
#zstyle ':dotzsh:module:theme:domain:example.net' theme 'dotphiles' 'soldark' 'red'

# Load dotzsh
source "$DOTZSH/init.zsh"

# Customize to your needs...

## Uncategorized Aliases ##########
alias vi="vim -p"

## ZSH Highlighting ##########
source /home/wesalvaro/third_party/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets pattern cursor)
ZSH_HIGHLIGHT_PATTERNS+=('\|' fg=magenta,bold)
zle_highlight=(region:standout special:standout suffix:bold isearch:underline)

## TMUX ##########
alias tmux='/home/wesalvaro/third_party/tmux/tmux-1.6/tmux'
alias xa='tmux at -t'
alias xd='tmux at -d -t'
alias xs='tmux new -s'
alias xls='tmux ls'
alias xl='tmux at'

## Git ##########
export GIT_CEILING_DIRECTORIES=/home/wesalvaro/src
alias g=git
alias gm="git5 merge"
alias b='git checkout -b'
alias lsb='git branch'
alias rmb='git branch -D'
alias mvb='git branch -m'
alias unci='git reset --soft HEAD~1'
alias cancel='git reset --hard HEAD'
alias rollback='git reset --hard HEAD~1'
alias co='git checkout'
function ca {
  local f="/home/wesalvaro/commits"
  if git commit -a -m "$1" >> $f; then
    echo "$(date) [$PWD]" >> $f
    echo >> $f
    tail -n5 $f
  fi;
}
function ci {
  local f="/home/wesalvaro/commits"
  if git commit -m "$1" >> $f; then
    echo $(date) [$PWD] >> $f
    echo >> $f
    tail -n5 $f
  fi;
}

# Z
. ~/third_party/z/z.sh
function precmd () {
  _z --add "$(pwd -P)"
}

## Google Proprietary ##########
if test -f ~/.zsh-goog; then
  source ~/.zsh-goog
fi;
